root: true

extends:
  - eslint:recommended

parserOptions:
  ecmaVersion: 11

env:
  es6: true
  node: true

rules:
  quotes: ["error", "double"]
  indent: "off"
  require-jsdoc: "off"
  eqeqeq: "off"
  curly: "off"
  no-invalid-this: "off"
  default-case: "off"
  no-nested-ternary: "off"
  no-underscore-dangle: "off"
  func-style: "off"
  new-cap: "off"
  callback-return: "off"
  no-loop-func: "off"
  prefer-const: "error"
  strict: ["error", "global"]
  semi: ["error", "always"]
  no-sequences: "error"
  dot-notation: "warn"
  dot-location: ["error", "property"]
  global-require: "error"
  no-path-concat: "error"
  prefer-arrow-callback: "error"
  no-var: "error"
